name: Refresh Build

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'
      id: go

    - name: Tidy
      run: go mod tidy

    - name: Test
      run: go test -v ./engine

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.0'

    - name: Dependencies
      run: go mod tidy

    - name: Build application
      run: go build ./cmd/refresh/

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: refresh
        path: ./refresh
